### ISSUE TITLE
get context feature

### ISSUE THREAD

**Issue by moebiussurfing** [Daandelange/ofxImGui#11]
Hey @Daandelange ,

How's going?

I am trying to implement some alignment of ImGui windows like here:
https://github.com/ocornut/imgui/issues/5287#issuecomment-1119473298

Do you think it could be useful to add a public context getter to `Gui.h`?

```.cpp
public:
  ImGuiContext* getContext() { return context; }
```

Then we can align doing something like:

```.cpp
//--------------------------------------------------------------
void doAlignWindows()
{
  ImGuiContext* GImGui = gui.getContext();
  ImGuiContext& g = *GImGui;
  {
	  ImVector<ImGuiWindow*> windows;
	  for (ImGuiWindow* window : g.WindowsFocusOrder)
		  if (window->WasActive)
			  windows.push_back(window);
  
	  if (windows.Size > 0)
	  {
		  ImVec2 base_pos = ImGui::GetMainViewport()->Pos;
  
		  ImVec2 v1 = ImVec2(0.7f, 0.7f);
  
		  ImVec2 step = ImFloor((ImGui::GetMainViewport()->Size * v1) / (float)windows.Size);
		  //step.x = step.y = ImFloor(ImMin(step.x, step.y));
  
		  for (int n = 0; n < windows.Size; n++)
		  {
			  ImVec2 v2 = ImVec2(((float)n + 0.5f), ((float)n + 0.5f));
			  ImGui::SetWindowPos(windows[n], base_pos + step * v2);
		  }
	  }
  }
}
```

Here is working like that.

Regards!

**Comment by Daandelange** [comment]
Hey manu ! :)
I think the ImGui philosophy is to provide ImGuiContext access only from plugin namespace / code.
The idea of providing an access to the context sounds great because it unlocks a lot of customization possibilities.
But it also exposes the underlying API to unstable results if used incorrectly, so I like the idea of clarifying "advanced usage" by  keeping the internals for extensions.

Maybe there's a better way of doing this without providing the full imgui context handle which exposes the internal API ?
Something ofxImGuiInternal ? Making your code a custom ImGuiEx (plugin) ?

In Mosaic [we solved it with a getContext](https://github.com/d3cod3/ofxVisualProgramming/blob/07d2ab6f348a9b74e31eaae2ef2a7bb4698ba036/src/core/imgui_node_canvas.h#L318) and [setContext](https://github.com/d3cod3/ofxVisualProgramming/blob/master/src/ofxVisualProgramming.cpp#L150), which is more of a workaround.

**Comment by moebiussurfing** [comment]
Cool thanks.
Is not required.
I didn't seen there were a method for that:

```
ImGuiContext* getContext() { 
  return ImGui::GetCurrentContext();
}
```

**Comment by Daandelange** [comment]
Yes, note that it doesn't guarantee to return the ofxImGui context (depending on when it's called), and there can be multiple in imgui so this might break over time.

**Comment by moebiussurfing** [comment]
ok. thanks.
but if it's called between begin/end (of ofxImGui methods (from one of the ofxImGui instances) should be fine?

**Comment by Daandelange** [comment]
For now, yes. Later it depends on how multi-windows, popout-windows and contexts evolve on the imgui side, hopefully easier to interface in-depth with openframeworks, on a lower level. Now, ofximgui "is a master" and doesn't share any stuff. (Way?) Later, there might be a way to share the same imgui instance with something that openframeworks isn't aware of, which might create other contexts, etc.)
